### ISSUE TITLE
视频变形

### ISSUE THREAD

**Issue by pisfans** [yangkun19921001/AVEditor#1]
大佬做的这个项目真好，想跟着学习一下，打算什么时候解决录制时和录制的合成视频变形的问题呢？

**Comment by yangkun19921001** [comment]
@pisfans 这个是因为录制采用竖屏模式，但是竖屏一般是 720*1280 分辨率。我暂时用的 1280*720 横屏模式下进行预览 ->编码->解码，所以导致了视频拉伸。后面我会单独解决这个问题，目前 ffmpeg AVCODE_ID_H264 解码 720*1280 会有问题。计划在国庆回来会单独解决这个问题。

**Comment by yangkun19921001** [comment]
@pisfans 录制画面拉伸已经修复，请更新最新代码。
